name: Cargo Test
on:
  push:
    paths:
      - 'cdnz/**'
      - 'editor/**'
      - 'Cargo.lock'
jobs:
  test:
    runs-on: codeberg-medium-lazy
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Cache Rust
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https:

      - name: Run tests
        run: cargo test --verbose
