on: [push]
jobs:
  test:
    runs-on: codeberg-small-lazy
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup Typst
        uses: https://github.com/chasewalden/setup-typst@v1
        with:
          version: '0.13.0'

      - name: Compile Typst to HTML
        run: |
          mkdir -p docs/output/html
          typst compile --features=html --format=html docs/src/main.typ docs/output/html/index.html

      - name: Publish to Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://${{ forge.repository_owner }}.codeberg.page/cadenza/'
          token: ${{ forge.token }}
          source: docs/output/html/
