name: Pages
on:
  push:
    paths:
      - 'docs/**'
jobs:
  deploy-pages:
    runs-on: codeberg-small-lazy
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup Python
        uses: https://code.forgejo.org/actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Zensical
        run: pip install zensical
      - name: Build site
        run: |
          cd docs
          zensical build

      - name: Deploy to Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://${{ forge.repository_owner }}.codeberg.page/cadenza/'
          token: ${{ forge.token }}
          source: docs/site/
